[package]
name = "rockpaperscissors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smitten = { path = "../smitten" }

[dependencies.rand]
version = "0.8.5"
features = ["std", "std_rng"]